### ISSUE TITLE
插件不支持mac？

### ISSUE THREAD

**Issue by shellingford37** [loonghfut/siyuan-link#1]
下载启用时提示不支持

**Comment by loonghfut** [comment]
我没有mac设备，没有测试过插件是否正常运行。故在插件配置文件里移除了mac和ios

**Comment by loonghfut** [comment]
0.1.6 我改了下插件配置文件，现在应该支持了，但没有经过简单测试（没有mac设备来测试）

**Comment by loonghfut** [comment]
0.1.6 我改了下插件配置文件，现在应该支持了，但没有经过简单测试（没有mac设备来测试）
