### ISSUE TITLE
请问如何将win客户端的思源同步到docker端呢？

### ISSUE THREAD

**Issue by NikoYomi** [loonghfut/siyuan-link#2]
在win上填写了思源服务器上的ip和端口，成功下载了服务器上docker部署的思源数据，但是怎么把win上的同步到docker呢？点了上传但是没看到显示成功的内容。

**Comment by loonghfut** [comment]
![tmp2CD4](https://github.com/user-attachments/assets/1775408d-b20e-4ef2-9409-02b41df80fcf)
你是点的这个吗

**Comment by loonghfut** [comment]
我这边测试是没有问题的，如果方便的话，请在使用传输功能时打开开发者工具，看看有没有报错。或提供相关截图

**Comment by NikoYomi** [comment]
> 我这边测试是没有问题的，如果方便的话，请在使用传输功能时打开开发者工具，看看有没有报错。或提供相关截图

我是window客户端，上传到docker部署的思源。所以在win客户端上填的docker的地址，然后点的全量传输。客户端上显示了收集的进度条，但直到完毕docker上部署的思源没有任何反应。你说的打开开发者工具，在客户端上怎么找到这个呢？

**Comment by loonghfut** [comment]
![tmp975A](https://github.com/user-attachments/assets/8f86b6cd-ea25-45f9-9d38-8dbfe9624248)
客户端上的开发者工具在这里

**Comment by loonghfut** [comment]
> > 我这边测试是没有问题的，如果方便的话，请在使用传输功能时打开开发者工具，看看有没有报错。或提供相关截图
> 
> 我是window客户端，上传到docker部署的思源。所以在win客户端上填的docker的地址，然后点的全量传输。客户端上显示了收集的进度条，但直到完毕docker上部署的思源没有任何反应。你说的打开开发者工具，在客户端上怎么找到这个呢？

win客户端的进度条完了，只是导出data文件，还需要等待data文件传输到目标源上，你在使用单笔记传输时有没有问题？当你使用全量传输时，右上角的消息有没有错误的反馈？

**Comment by loonghfut** [comment]
全量传输和全量拉取，如果文件比较大，会非常耗时间，一般不用于同步，主要用于第一次部署docker思源或者第一次使用win版的思源时进行数据导入

**Comment by NikoYomi** [comment]
已解决！感谢你的帮助，也感谢你开发的插件！！
