### ISSUE TITLE
无法连接docker上的网址，实际本地可以打开

### ISSUE THREAD

**Issue by riiiccck** [loonghfut/siyuan-link#5]
实际填写 http://192.168.56.31:6831 
网页上也可以打开 http://192.168.56.31:6831
但提示服务器连接失败

**Comment by loonghfut** [comment]
![tmpE735](https://github.com/user-attachments/assets/3ad263c8-0525-44cd-857e-fbf5ce09bdbf)
![tmp8F63](https://github.com/user-attachments/assets/4ac8a9a5-7c09-4c3e-9f18-105d1714dae9)
我这边测试没问题，如果方便，麻烦提供相关截图（注意不要暴露个人信息）和打开开发者选项复制一下插件日志

**Comment by XiaoGe-LiBai** [comment]
![image](https://github.com/user-attachments/assets/41af9a2b-bd77-42bd-98d4-fbcb3143623c)
![image](https://github.com/user-attachments/assets/3ced965f-6220-4d61-a342-0a3e85d981e6)
![image](https://github.com/user-attachments/assets/d3c8f6ca-78a6-4ca3-a417-42c498833f63)
我的docker版可以验证通过Windows的地址反之不行
![image](https://github.com/user-attachments/assets/d37dcc2c-f737-4165-9f99-89f50be4d2d1)

**Comment by loonghfut** [comment]
> 我的docker版可以验证通过Windows的地址反之不行

因为你的docker版的思源无法访问到你的window端，win端你填的是局域网地址外网访问不了
